fix: keycloak plugin issues
cloudforet-io/plugin-keycloak-identity-auth pull request #7
Opened 2023-11-07 04:18 UTC by chulgyu-jeon

1. Add env KEYCLOAK_API_BASE_PATH to set admin api path  for keycloak  version 18++
2 .Fix hardcoded "verify" values  to support private root ca path
---
plugin_info:
  options:
    auth_type: keycloak_oidc
    openid-configuration: https://keycloak.example.com/realms/service/.well-known/openid-configuration
    client_id: keycloak
    verify: "/opt/ssl/certs/sample.crt"

2023-11-10 11:09 UTC, whdalsrnt requested changes
Hi, @chulgyu-jeon 

Thank you for your PR.

When setting custom values for Cloudforet's plugin, `options` parameter is better than `environment`.

So change your code.

Thanks.

2023-11-13 01:21 UTC, chulgyu-jeon commented
fix code to support keycloak admin url base path with options

2023-11-13 01:21 UTC, chulgyu-jeon commented
> Hi, @chulgyu-jeon
> 
> Thank you for your PR.
> 
> When setting custom values for Cloudforet's plugin, `options` parameter is better than `environment`.
> 
> So change your code.
> 
> Thanks.

fix code to support keycloak admin url base path with options

2023-11-13 10:07 UTC, whdalsrnt approved these changes
Great!

Thank you for the quick change.

2023-11-13 10:07 UTC, whdalsrnt commented on src/spaceone/identity/connector/keycloak_connector.py
> +    base_path = os.environ.get("KEYCLOAK_API_BASE_PATH", "/auth/admin/realms/")
Use options instead of environment.
And the variable name is suggested as `keycloak_base_url`.

2023-11-13 10:07 UTC, merged